name: Lập trình cuộc sống
description: Chỉ là blog của một thằng coder
seo_description: Lập trình cuộc sống, blog  về kỹ thuật, rèn luyện kỹ năng và chia sẻ  kinh nghiệm phát triển bản thân dành cho tất cả lập trình viên
avatar: images/logo.gif
baseurl: 
site_url: "http://laptrinhcuocsong.com"
default_post_avatar: images/logo.gif
permalink: /:title.html
version: v1.2.0
markdown: kramdown
syntax_highlighter: rouge
tags_config:
  hacking-co-ban:
    name: Hacking cơ bản
  hoc-hack-co-ban:
    name: Học hack cơ bản
  hoc-ubuntu:
    name: Học ubuntu
  lap-trinh-game-bang-javascript:
    name: Lập trình game javascript
  lap-trinh-javascript:
    name: Lập trình javascript
  lap-trinh-mot-game-don-gian:
    name: Lập trình game đơn giản
  tu-hoc-linux:
    name: Tự học linux
  jquery:
    name: Jquery
sass:
  style: :compressed
gems:
  - jekyll-sitemap
  - jekyll-feed
  - jemoji
defaults:
  values:
    layout: "post"
# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CNAME
  
# paginate
paginate: 15
